### PR TITLE
fix css in create event form to correct div placement on other pages

### LINKED ISSUE #24: Fix styling in eventform
Event form has styling that is effecting other pages.  Need to update the EventForm.css to correct issue.

### PR DESCRIPTION
**Pull request by tfoxcollis**
## Summary
Updated html element in eventform.css that was effecting other pages.  

## Type of Changes:
- [ ] Bug fix
- [x] Refactor
- [ ] New feature

## What are the relevant tickets:
closes #24

### CODE REVIEW

File: src/Components/EventForm/EventForm.js [hunk 1]
```diff
@@ -16,8 +16,8 @@ export default function EventForm() {
 
   return (
     <div className='form-wrapper'>
-      <form>
-        <h1>Create A New Event</h1>
+      <form className="event-form">
+        <h1 className="form-header">Create A New Event</h1>
         <input className='event-input' onChange={handleChange} type='text' placeholder='Add Title' name='title' value={eventDetails.title}/>
```
Comment (BlueNealis) [inline src/Components/EventForm/EventForm.js:21]: Thanks for fixing this !!

**Review by BlueNealis — APPROVED** [review]
